### ISSUE TITLE
Could not get code signature when starting the app.

### ISSUE THREAD

**Issue by Arjanvde** [athombv/node-athom-gui#8] opened 2016-06-27 17:10 UTC
Not sure if this error message is known? On version 0.0.8 when loggin in the follow message appears.

![schermafbeelding 2016-06-27 om 19 08 26](https://cloud.githubusercontent.com/assets/17526110/16388713/99f9d118-3c9a-11e6-94eb-e8ca7e9a1ae4.png)

Also had to manually update from version 0.0.7 as it would not update through the update process.

**Comment by TheMSB** [comment] 2016-06-28 07:16
It is a known issue, something went wrong with signing the latest release, It will be fixed in the next one.

**Comment by matjaz** [comment] 2016-06-28 07:22
This could happen if 0.0.7 & 0.0.8 uses different certificates.

**Comment by TheMSB** [comment] 2016-06-28 08:42
The problem is that the 0.0.8 version is actually unsigned right now. As I stated before it will be fixed in the next release.

**Comment by TheMSB** [comment] 2016-07-01 20:32
fixed in 0.1.0

**Closed by TheMSB** 2016-07-01 20:32 UTC
